/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjsUserProfileShort struct {
	AvatarHash string `json:"avatar_hash"`
	DisplayName string `json:"display_name"`
	FirstName string `json:"first_name"`
	Image72 string `json:"image_72"`
	IsRestricted bool `json:"is_restricted"`
	IsUltraRestricted bool `json:"is_ultra_restricted"`
	Name string `json:"name"`
	RealName string `json:"real_name"`
	Team *DefsWorkspaceId `json:"team"`
}
