/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjsEnterpriseUser struct {
	EnterpriseId *DefsEnterpriseId `json:"enterprise_id"`
	EnterpriseName *DefsEnterpriseName `json:"enterprise_name"`
	Id *DefsEnterpriseUserId `json:"id"`
	IsAdmin bool `json:"is_admin"`
	IsOwner bool `json:"is_owner"`
	Teams []DefsTeam `json:"teams"`
}
