/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjsGroup struct {
	Created int32 `json:"created"`
	Creator *DefsUserId `json:"creator"`
	Id *DefsGroupId `json:"id"`
	IsArchived bool `json:"is_archived,omitempty"`
	IsDeleted bool `json:"is_deleted,omitempty"`
	IsGroup bool `json:"is_group"`
	IsMoved int32 `json:"is_moved,omitempty"`
	IsMpim bool `json:"is_mpim,omitempty"`
	IsOpen bool `json:"is_open,omitempty"`
	IsPendingExtShared bool `json:"is_pending_ext_shared,omitempty"`
	LastRead *DefsTs `json:"last_read,omitempty"`
	Latest *interface{} `json:"latest,omitempty"`
	Members []DefsUserId `json:"members"`
	Name string `json:"name"`
	NameNormalized string `json:"name_normalized"`
	NumMembers int32 `json:"num_members,omitempty"`
	Priority float32 `json:"priority,omitempty"`
	Purpose *ObjsChannelPurpose `json:"purpose"`
	Topic *ObjsChannelPurpose `json:"topic"`
	UnreadCount int32 `json:"unread_count,omitempty"`
	UnreadCountDisplay int32 `json:"unread_count_display,omitempty"`
}
