/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjsFile struct {
	Channels []DefsChannelId `json:"channels,omitempty"`
	CommentsCount int32 `json:"comments_count,omitempty"`
	Created int32 `json:"created,omitempty"`
	DisplayAsBot bool `json:"display_as_bot,omitempty"`
	Editable bool `json:"editable,omitempty"`
	Editor *DefsUserId `json:"editor,omitempty"`
	ExternalId string `json:"external_id,omitempty"`
	ExternalType string `json:"external_type,omitempty"`
	ExternalUrl string `json:"external_url,omitempty"`
	Filetype string `json:"filetype,omitempty"`
	Groups []DefsGroupId `json:"groups,omitempty"`
	HasRichPreview bool `json:"has_rich_preview,omitempty"`
	Id *DefsFileId `json:"id,omitempty"`
	ImageExifRotation int32 `json:"image_exif_rotation,omitempty"`
	Ims []DefsDmId `json:"ims,omitempty"`
	IsExternal bool `json:"is_external,omitempty"`
	IsPublic bool `json:"is_public,omitempty"`
	IsStarred bool `json:"is_starred,omitempty"`
	IsTombstoned bool `json:"is_tombstoned,omitempty"`
	LastEditor *DefsUserId `json:"last_editor,omitempty"`
	Mimetype string `json:"mimetype,omitempty"`
	Mode string `json:"mode,omitempty"`
	Name string `json:"name,omitempty"`
	NumStars int32 `json:"num_stars,omitempty"`
	OriginalH int32 `json:"original_h,omitempty"`
	OriginalW int32 `json:"original_w,omitempty"`
	Permalink string `json:"permalink,omitempty"`
	PermalinkPublic string `json:"permalink_public,omitempty"`
	PinnedInfo *DefsPinnedInfo `json:"pinned_info,omitempty"`
	PinnedTo []DefsChannel `json:"pinned_to,omitempty"`
	PrettyType string `json:"pretty_type,omitempty"`
	PublicUrlShared bool `json:"public_url_shared,omitempty"`
	Reactions []ObjsReaction `json:"reactions,omitempty"`
	Shares *ObjsFileShares `json:"shares,omitempty"`
	Size int32 `json:"size,omitempty"`
	SourceTeam *DefsTeam `json:"source_team,omitempty"`
	State string `json:"state,omitempty"`
	Thumb1024 string `json:"thumb_1024,omitempty"`
	Thumb1024H int32 `json:"thumb_1024_h,omitempty"`
	Thumb1024W int32 `json:"thumb_1024_w,omitempty"`
	Thumb160 string `json:"thumb_160,omitempty"`
	Thumb360 string `json:"thumb_360,omitempty"`
	Thumb360H int32 `json:"thumb_360_h,omitempty"`
	Thumb360W int32 `json:"thumb_360_w,omitempty"`
	Thumb480 string `json:"thumb_480,omitempty"`
	Thumb480H int32 `json:"thumb_480_h,omitempty"`
	Thumb480W int32 `json:"thumb_480_w,omitempty"`
	Thumb64 string `json:"thumb_64,omitempty"`
	Thumb720 string `json:"thumb_720,omitempty"`
	Thumb720H int32 `json:"thumb_720_h,omitempty"`
	Thumb720W int32 `json:"thumb_720_w,omitempty"`
	Thumb80 string `json:"thumb_80,omitempty"`
	Thumb800 string `json:"thumb_800,omitempty"`
	Thumb800H int32 `json:"thumb_800_h,omitempty"`
	Thumb800W int32 `json:"thumb_800_w,omitempty"`
	Thumb960 string `json:"thumb_960,omitempty"`
	Thumb960H int32 `json:"thumb_960_h,omitempty"`
	Thumb960W int32 `json:"thumb_960_w,omitempty"`
	Timestamp int32 `json:"timestamp,omitempty"`
	Title string `json:"title,omitempty"`
	Updated int32 `json:"updated,omitempty"`
	UrlPrivate string `json:"url_private,omitempty"`
	UrlPrivateDownload string `json:"url_private_download,omitempty"`
	User string `json:"user,omitempty"`
	UserTeam *DefsTeam `json:"user_team,omitempty"`
	Username string `json:"username,omitempty"`
}
