/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjsIcon struct {
	Image102 string `json:"image_102,omitempty"`
	Image132 string `json:"image_132,omitempty"`
	Image230 string `json:"image_230,omitempty"`
	Image34 string `json:"image_34,omitempty"`
	Image44 string `json:"image_44,omitempty"`
	Image68 string `json:"image_68,omitempty"`
	Image88 string `json:"image_88,omitempty"`
	ImageDefault bool `json:"image_default,omitempty"`
}
