/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjsTeamProfileField struct {
	FieldName string `json:"field_name,omitempty"`
	Hint string `json:"hint"`
	Id string `json:"id"`
	IsHidden bool `json:"is_hidden,omitempty"`
	Label string `json:"label"`
	Options []string `json:"options"`
	Ordering float32 `json:"ordering"`
	PossibleValues []string `json:"possible_values,omitempty"`
	Type_ string `json:"type"`
}
