/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjsReminder struct {
	CompleteTs int32 `json:"complete_ts,omitempty"`
	Creator *DefsUserId `json:"creator"`
	Id *DefsReminderId `json:"id"`
	Recurring bool `json:"recurring"`
	Text string `json:"text"`
	Time int32 `json:"time,omitempty"`
	User *DefsUserId `json:"user"`
}
