/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjsSubteam struct {
	AutoProvision bool `json:"auto_provision"`
	AutoType *interface{} `json:"auto_type"`
	CreatedBy *DefsUserId `json:"created_by"`
	DateCreate int32 `json:"date_create"`
	DateDelete int32 `json:"date_delete"`
	DateUpdate int32 `json:"date_update"`
	DeletedBy *interface{} `json:"deleted_by"`
	Description string `json:"description"`
	EnterpriseSubteamId string `json:"enterprise_subteam_id"`
	Handle string `json:"handle"`
	Id *DefsSubteamId `json:"id"`
	IsExternal bool `json:"is_external"`
	IsSubteam bool `json:"is_subteam"`
	IsUsergroup bool `json:"is_usergroup"`
	Name string `json:"name"`
	Prefs *ObjsSubteamPrefs `json:"prefs"`
	TeamId *DefsTeam `json:"team_id"`
	UpdatedBy *DefsUserId `json:"updated_by"`
	UserCount int32 `json:"user_count,omitempty"`
	Users []DefsUserId `json:"users,omitempty"`
}
