---
swagger: "2.0"
info:
  description: "One way to interact with the Slack platform is its HTTP RPC-based\
    \ Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace\
    \ tokens blessed with related OAuth scopes."
  version: "1.2.0"
  title: "Slack Web API"
host: "slack.com"
basePath: "/api"
schemes:
- "https"
paths:
  /admin.users.session.reset:
    post:
      tags:
      - "admin.users.session"
      - "admin"
      description: "Wipes all valid sessions on all devices for a given user"
      operationId: "admin_users_session_reset"
      security:
      - slackAuth:
        - "admin.users:write"
  /api.test:
    get:
      tags:
      - "api"
      description: "Checks API calling code."
      operationId: "api_test"
      security:
      - slackAuth:
        - "none"
  /apps.permissions.info:
    get:
      tags:
      - "apps.permissions"
      - "apps"
      description: "Returns list of permissions this app has on a team."
      operationId: "apps_permissions_info"
      security:
      - slackAuth:
        - "none"
  /apps.permissions.request:
    get:
      tags:
      - "apps.permissions"
      - "apps"
      description: "Allows an app to request additional scopes"
      operationId: "apps_permissions_request"
      security:
      - slackAuth:
        - "none"
  /apps.permissions.resources.list:
    get:
      tags:
      - "apps.permissions.resources"
      - "apps"
      description: "Returns list of resource grants this app has on a team."
      operationId: "apps_permissions_resources_list"
      security:
      - slackAuth:
        - "none"
  /apps.permissions.scopes.list:
    get:
      tags:
      - "apps.permissions.scopes"
      - "apps"
      description: "Returns list of scopes this app has on a team."
      operationId: "apps_permissions_scopes_list"
      security:
      - slackAuth:
        - "none"
  /apps.permissions.users.list:
    get:
      tags:
      - "apps.permissions.users"
      - "apps"
      description: "Returns list of user grants and corresponding scopes this app\
        \ has on a team."
      operationId: "apps_permissions_users_list"
      security:
      - slackAuth:
        - "none"
  /apps.permissions.users.request:
    get:
      tags:
      - "apps.permissions.users"
      - "apps"
      description: "Enables an app to trigger a permissions modal to grant an app\
        \ access to a user access scope."
      operationId: "apps_permissions_users_request"
      security:
      - slackAuth:
        - "none"
  /apps.uninstall:
    get:
      tags:
      - "apps"
      description: "Uninstalls your app from a workspace."
      operationId: "apps_uninstall"
      security:
      - slackAuth:
        - "none"
  /auth.revoke:
    get:
      tags:
      - "auth"
      description: "Revokes a token."
      operationId: "auth_revoke"
      security:
      - slackAuth:
        - "none"
  /auth.test:
    get:
      tags:
      - "auth"
      description: "Checks authentication & identity."
      operationId: "auth_test"
      security:
      - slackAuth:
        - "none"
  /bots.info:
    get:
      tags:
      - "bots"
      description: "Gets information about a bot user."
      operationId: "bots_info"
      security:
      - slackAuth:
        - "users:read"
  /channels.archive:
    post:
      tags:
      - "channels"
      description: "Archives a channel."
      operationId: "channels_archive"
      security:
      - slackAuth:
        - "channels:write"
  /channels.create:
    post:
      tags:
      - "channels"
      description: "Creates a channel."
      operationId: "channels_create"
      security:
      - slackAuth:
        - "channels:write"
  /channels.history:
    get:
      tags:
      - "channels"
      description: "Fetches history of messages and events from a channel."
      operationId: "channels_history"
      security:
      - slackAuth:
        - "channels:history"
  /channels.info:
    get:
      tags:
      - "channels"
      description: "Gets information about a channel."
      operationId: "channels_info"
      security:
      - slackAuth:
        - "channels:read"
  /channels.invite:
    post:
      tags:
      - "channels"
      description: "Invites a user to a channel."
      operationId: "channels_invite"
      security:
      - slackAuth:
        - "channels:write"
  /channels.join:
    post:
      tags:
      - "channels"
      description: "Joins a channel, creating it if needed."
      operationId: "channels_join"
      security:
      - slackAuth:
        - "channels:write"
  /channels.kick:
    post:
      tags:
      - "channels"
      description: "Removes a user from a channel."
      operationId: "channels_kick"
      security:
      - slackAuth:
        - "channels:write"
  /channels.leave:
    post:
      tags:
      - "channels"
      description: "Leaves a channel."
      operationId: "channels_leave"
      security:
      - slackAuth:
        - "channels:write"
  /channels.list:
    get:
      tags:
      - "channels"
      description: "Lists all channels in a Slack team."
      operationId: "channels_list"
      security:
      - slackAuth:
        - "channels:read"
  /channels.mark:
    post:
      tags:
      - "channels"
      description: "Sets the read cursor in a channel."
      operationId: "channels_mark"
      security:
      - slackAuth:
        - "channels:write"
  /channels.rename:
    post:
      tags:
      - "channels"
      description: "Renames a channel."
      operationId: "channels_rename"
      security:
      - slackAuth:
        - "channels:write"
  /channels.replies:
    get:
      tags:
      - "channels"
      description: "Retrieve a thread of messages posted to a channel"
      operationId: "channels_replies"
      security:
      - slackAuth:
        - "channels:history"
  /channels.setPurpose:
    post:
      tags:
      - "channels"
      description: "Sets the purpose for a channel."
      operationId: "channels_setPurpose"
      security:
      - slackAuth:
        - "channels:write"
  /channels.setTopic:
    post:
      tags:
      - "channels"
      description: "Sets the topic for a channel."
      operationId: "channels_setTopic"
      security:
      - slackAuth:
        - "channels:write"
  /channels.unarchive:
    post:
      tags:
      - "channels"
      description: "Unarchives a channel."
      operationId: "channels_unarchive"
      security:
      - slackAuth:
        - "channels:write"
  /chat.delete:
    post:
      tags:
      - "chat"
      description: "Deletes a message."
      operationId: "chat_delete"
      security:
      - slackAuth:
        - "chat:write:user"
        - "chat:write:bot"
  /chat.deleteScheduledMessage:
    post:
      tags:
      - "chat"
      description: "Deletes a pending scheduled message from the queue."
      operationId: "chat_deleteScheduledMessage"
      security:
      - slackAuth:
        - "chat:write:user"
        - "chat:write:bot"
  /chat.getPermalink:
    get:
      tags:
      - "chat"
      description: "Retrieve a permalink URL for a specific extant message"
      operationId: "chat_getPermalink"
      security:
      - slackAuth:
        - "none"
  /chat.meMessage:
    post:
      tags:
      - "chat"
      description: "Share a me message into a channel."
      operationId: "chat_meMessage"
      security:
      - slackAuth:
        - "chat:write:user"
  /chat.postEphemeral:
    post:
      tags:
      - "chat"
      description: "Sends an ephemeral message to a user in a channel."
      operationId: "chat_postEphemeral"
      security:
      - slackAuth:
        - "chat:write:user"
        - "chat:write:bot"
  /chat.postMessage:
    post:
      tags:
      - "chat"
      description: "Sends a message to a channel."
      operationId: "chat_postMessage"
      security:
      - slackAuth:
        - "chat:write:user"
        - "chat:write:bot"
  /chat.scheduleMessage:
    post:
      tags:
      - "chat"
      description: "Schedules a message to be sent to a channel."
      operationId: "chat_scheduleMessage"
      security:
      - slackAuth:
        - "chat:write:user"
        - "chat:write:bot"
  /chat.scheduledMessages.list:
    get:
      tags:
      - "chat.scheduledMessages"
      - "chat"
      description: "Returns a list of scheduled messages."
      operationId: "chat_scheduledMessages_list"
      security:
      - slackAuth:
        - "none"
  /chat.unfurl:
    post:
      tags:
      - "chat"
      description: "Provide custom unfurl behavior for user-posted URLs"
      operationId: "chat_unfurl"
      security:
      - slackAuth:
        - "links:write"
  /chat.update:
    post:
      tags:
      - "chat"
      description: "Updates a message."
      operationId: "chat_update"
      security:
      - slackAuth:
        - "chat:write:user"
        - "chat:write:bot"
  /conversations.archive:
    post:
      tags:
      - "conversations"
      description: "Archives a conversation."
      operationId: "conversations_archive"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.close:
    post:
      tags:
      - "conversations"
      description: "Closes a direct message or multi-person direct message."
      operationId: "conversations_close"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.create:
    post:
      tags:
      - "conversations"
      description: "Initiates a public or private channel-based conversation"
      operationId: "conversations_create"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.history:
    get:
      tags:
      - "conversations"
      description: "Fetches a conversation's history of messages and events."
      operationId: "conversations_history"
      security:
      - slackAuth:
        - "channels:history"
        - "groups:history"
        - "im:history"
        - "mpim:history"
  /conversations.info:
    get:
      tags:
      - "conversations"
      description: "Retrieve information about a conversation."
      operationId: "conversations_info"
      security:
      - slackAuth:
        - "channels:read"
        - "groups:read"
        - "im:read"
        - "mpim:read"
  /conversations.invite:
    post:
      tags:
      - "conversations"
      description: "Invites users to a channel."
      operationId: "conversations_invite"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.join:
    post:
      tags:
      - "conversations"
      description: "Joins an existing conversation."
      operationId: "conversations_join"
      security:
      - slackAuth:
        - "channels:write"
  /conversations.kick:
    post:
      tags:
      - "conversations"
      description: "Removes a user from a conversation."
      operationId: "conversations_kick"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.leave:
    post:
      tags:
      - "conversations"
      description: "Leaves a conversation."
      operationId: "conversations_leave"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.list:
    get:
      tags:
      - "conversations"
      description: "Lists all channels in a Slack team."
      operationId: "conversations_list"
      security:
      - slackAuth:
        - "channels:read"
        - "groups:read"
        - "im:read"
        - "mpim:read"
  /conversations.members:
    get:
      tags:
      - "conversations"
      description: "Retrieve members of a conversation."
      operationId: "conversations_members"
      security:
      - slackAuth:
        - "channels:read"
        - "groups:read"
        - "im:read"
        - "mpim:read"
  /conversations.open:
    post:
      tags:
      - "conversations"
      description: "Opens or resumes a direct message or multi-person direct message."
      operationId: "conversations_open"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.rename:
    post:
      tags:
      - "conversations"
      description: "Renames a conversation."
      operationId: "conversations_rename"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.replies:
    get:
      tags:
      - "conversations"
      description: "Retrieve a thread of messages posted to a conversation"
      operationId: "conversations_replies"
      security:
      - slackAuth:
        - "channels:history"
        - "groups:history"
        - "im:history"
        - "mpim:history"
  /conversations.setPurpose:
    post:
      tags:
      - "conversations"
      description: "Sets the purpose for a conversation."
      operationId: "conversations_setPurpose"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.setTopic:
    post:
      tags:
      - "conversations"
      description: "Sets the topic for a conversation."
      operationId: "conversations_setTopic"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /conversations.unarchive:
    post:
      tags:
      - "conversations"
      description: "Reverses conversation archival."
      operationId: "conversations_unarchive"
      security:
      - slackAuth:
        - "channels:write"
        - "groups:write"
        - "im:write"
        - "mpim:write"
  /dialog.open:
    get:
      tags:
      - "dialog"
      description: "Open a dialog with a user"
      operationId: "dialog_open"
      security:
      - slackAuth:
        - "none"
  /dnd.endDnd:
    post:
      tags:
      - "dnd"
      description: "Ends the current user's Do Not Disturb session immediately."
      operationId: "dnd_endDnd"
      security:
      - slackAuth:
        - "dnd:write"
  /dnd.endSnooze:
    post:
      tags:
      - "dnd"
      description: "Ends the current user's snooze mode immediately."
      operationId: "dnd_endSnooze"
      security:
      - slackAuth:
        - "dnd:write"
  /dnd.info:
    get:
      tags:
      - "dnd"
      description: "Retrieves a user's current Do Not Disturb status."
      operationId: "dnd_info"
      security:
      - slackAuth:
        - "dnd:read"
  /dnd.setSnooze:
    post:
      tags:
      - "dnd"
      description: "Turns on Do Not Disturb mode for the current user, or changes\
        \ its duration."
      operationId: "dnd_setSnooze"
      security:
      - slackAuth:
        - "dnd:write"
  /dnd.teamInfo:
    get:
      tags:
      - "dnd"
      description: "Retrieves the Do Not Disturb status for up to 50 users on a team."
      operationId: "dnd_teamInfo"
      security:
      - slackAuth:
        - "dnd:read"
  /emoji.list:
    get:
      tags:
      - "emoji"
      description: "Lists custom emoji for a team."
      operationId: "emoji_list"
      security:
      - slackAuth:
        - "emoji:read"
  /files.comments.delete:
    post:
      tags:
      - "files.comments"
      - "files"
      description: "Deletes an existing comment on a file."
      operationId: "files_comments_delete"
      security:
      - slackAuth:
        - "files:write:user"
  /files.delete:
    post:
      tags:
      - "files"
      description: "Deletes a file."
      operationId: "files_delete"
      security:
      - slackAuth:
        - "files:write:user"
  /files.info:
    get:
      tags:
      - "files"
      description: "Gets information about a team file."
      operationId: "files_info"
      security:
      - slackAuth:
        - "files:read"
  /files.list:
    get:
      tags:
      - "files"
      description: "Lists & filters team files."
      operationId: "files_list"
      security:
      - slackAuth:
        - "files:read"
  /files.revokePublicURL:
    post:
      tags:
      - "files"
      description: "Revokes public/external sharing access for a file"
      operationId: "files_revokePublicURL"
      security:
      - slackAuth:
        - "files:write:user"
  /files.sharedPublicURL:
    post:
      tags:
      - "files"
      description: "Enables a file for public/external sharing."
      operationId: "files_sharedPublicURL"
      security:
      - slackAuth:
        - "files:write:user"
  /files.upload:
    post:
      tags:
      - "files"
      description: "Uploads or creates a file."
      operationId: "files_upload"
      security:
      - slackAuth:
        - "files:write:user"
  /groups.archive:
    post:
      tags:
      - "groups"
      description: "Archives a private channel."
      operationId: "groups_archive"
      security:
      - slackAuth:
        - "groups:write"
  /groups.create:
    post:
      tags:
      - "groups"
      description: "Creates a private channel."
      operationId: "groups_create"
      security:
      - slackAuth:
        - "groups:write"
  /groups.createChild:
    post:
      tags:
      - "groups"
      description: "Clones and archives a private channel."
      operationId: "groups_createChild"
      security:
      - slackAuth:
        - "groups:write"
  /groups.history:
    get:
      tags:
      - "groups"
      description: "Fetches history of messages and events from a private channel."
      operationId: "groups_history"
      security:
      - slackAuth:
        - "groups:history"
  /groups.info:
    get:
      tags:
      - "groups"
      description: "Gets information about a private channel."
      operationId: "groups_info"
      security:
      - slackAuth:
        - "groups:read"
  /groups.invite:
    post:
      tags:
      - "groups"
      description: "Invites a user to a private channel."
      operationId: "groups_invite"
      security:
      - slackAuth:
        - "groups:write"
  /groups.kick:
    post:
      tags:
      - "groups"
      description: "Removes a user from a private channel."
      operationId: "groups_kick"
      security:
      - slackAuth:
        - "groups:write"
  /groups.leave:
    post:
      tags:
      - "groups"
      description: "Leaves a private channel."
      operationId: "groups_leave"
      security:
      - slackAuth:
        - "groups:write"
  /groups.list:
    get:
      tags:
      - "groups"
      description: "Lists private channels that the calling user has access to."
      operationId: "groups_list"
      security:
      - slackAuth:
        - "groups:read"
  /groups.mark:
    post:
      tags:
      - "groups"
      description: "Sets the read cursor in a private channel."
      operationId: "groups_mark"
      security:
      - slackAuth:
        - "groups:write"
  /groups.open:
    post:
      tags:
      - "groups"
      description: "Opens a private channel."
      operationId: "groups_open"
      security:
      - slackAuth:
        - "groups:write"
  /groups.rename:
    post:
      tags:
      - "groups"
      description: "Renames a private channel."
      operationId: "groups_rename"
      security:
      - slackAuth:
        - "groups:write"
  /groups.replies:
    get:
      tags:
      - "groups"
      description: "Retrieve a thread of messages posted to a private channel"
      operationId: "groups_replies"
      security:
      - slackAuth:
        - "groups:history"
  /groups.setPurpose:
    post:
      tags:
      - "groups"
      description: "Sets the purpose for a private channel."
      operationId: "groups_setPurpose"
      security:
      - slackAuth:
        - "groups:write"
  /groups.setTopic:
    post:
      tags:
      - "groups"
      description: "Sets the topic for a private channel."
      operationId: "groups_setTopic"
      security:
      - slackAuth:
        - "groups:write"
  /groups.unarchive:
    post:
      tags:
      - "groups"
      description: "Unarchives a private channel."
      operationId: "groups_unarchive"
      security:
      - slackAuth:
        - "groups:write"
  /im.close:
    post:
      tags:
      - "im"
      description: "Close a direct message channel."
      operationId: "im_close"
      security:
      - slackAuth:
        - "im:write"
  /im.history:
    get:
      tags:
      - "im"
      description: "Fetches history of messages and events from direct message channel."
      operationId: "im_history"
      security:
      - slackAuth:
        - "im:history"
  /im.list:
    get:
      tags:
      - "im"
      description: "Lists direct message channels for the calling user."
      operationId: "im_list"
      security:
      - slackAuth:
        - "im:read"
  /im.mark:
    post:
      tags:
      - "im"
      description: "Sets the read cursor in a direct message channel."
      operationId: "im_mark"
      security:
      - slackAuth:
        - "im:write"
  /im.open:
    post:
      tags:
      - "im"
      description: "Opens a direct message channel."
      operationId: "im_open"
      security:
      - slackAuth:
        - "im:write"
  /im.replies:
    get:
      tags:
      - "im"
      description: "Retrieve a thread of messages posted to a direct message conversation"
      operationId: "im_replies"
      security:
      - slackAuth:
        - "im:history"
  /migration.exchange:
    get:
      tags:
      - "migration"
      description: "For Enterprise Grid workspaces, map local user IDs to global user\
        \ IDs"
      operationId: "migration_exchange"
      security:
      - slackAuth:
        - "tokens.basic"
  /mpim.close:
    post:
      tags:
      - "mpim"
      description: "Closes a multiparty direct message channel."
      operationId: "mpim_close"
      security:
      - slackAuth:
        - "mpim:write"
  /mpim.history:
    get:
      tags:
      - "mpim"
      description: "Fetches history of messages and events from a multiparty direct\
        \ message."
      operationId: "mpim_history"
      security:
      - slackAuth:
        - "mpim:history"
  /mpim.list:
    get:
      tags:
      - "mpim"
      description: "Lists multiparty direct message channels for the calling user."
      operationId: "mpim_list"
      security:
      - slackAuth:
        - "mpim:read"
  /mpim.mark:
    post:
      tags:
      - "mpim"
      description: "Sets the read cursor in a multiparty direct message channel."
      operationId: "mpim_mark"
      security:
      - slackAuth:
        - "mpim:write"
  /mpim.open:
    post:
      tags:
      - "mpim"
      description: "This method opens a multiparty direct message."
      operationId: "mpim_open"
      security:
      - slackAuth:
        - "mpim:write"
  /mpim.replies:
    get:
      tags:
      - "mpim"
      description: "Retrieve a thread of messages posted to a direct message conversation\
        \ from a multiparty direct message."
      operationId: "mpim_replies"
      security:
      - slackAuth:
        - "mpim:history"
  /oauth.access:
    get:
      tags:
      - "oauth"
      description: "Exchanges a temporary OAuth verifier code for an access token."
      operationId: "oauth_access"
      security:
      - slackAuth:
        - "none"
  /oauth.token:
    get:
      tags:
      - "oauth"
      description: "Exchanges a temporary OAuth verifier code for a workspace token."
      operationId: "oauth_token"
      security:
      - slackAuth:
        - "none"
  /pins.add:
    post:
      tags:
      - "pins"
      description: "Pins an item to a channel."
      operationId: "pins_add"
      security:
      - slackAuth:
        - "pins:write"
  /pins.list:
    get:
      tags:
      - "pins"
      description: "Lists items pinned to a channel."
      operationId: "pins_list"
      security:
      - slackAuth:
        - "pins:read"
  /pins.remove:
    post:
      tags:
      - "pins"
      description: "Un-pins an item from a channel."
      operationId: "pins_remove"
      security:
      - slackAuth:
        - "pins:write"
  /reactions.add:
    post:
      tags:
      - "reactions"
      description: "Adds a reaction to an item."
      operationId: "reactions_add"
      security:
      - slackAuth:
        - "reactions:write"
  /reactions.get:
    get:
      tags:
      - "reactions"
      description: "Gets reactions for an item."
      operationId: "reactions_get"
      security:
      - slackAuth:
        - "reactions:read"
  /reactions.list:
    get:
      tags:
      - "reactions"
      description: "Lists reactions made by a user."
      operationId: "reactions_list"
      security:
      - slackAuth:
        - "reactions:read"
  /reactions.remove:
    post:
      tags:
      - "reactions"
      description: "Removes a reaction from an item."
      operationId: "reactions_remove"
      security:
      - slackAuth:
        - "reactions:write"
  /reminders.add:
    post:
      tags:
      - "reminders"
      description: "Creates a reminder."
      operationId: "reminders_add"
      security:
      - slackAuth:
        - "reminders:write"
  /reminders.complete:
    post:
      tags:
      - "reminders"
      description: "Marks a reminder as complete."
      operationId: "reminders_complete"
      security:
      - slackAuth:
        - "reminders:write"
  /reminders.delete:
    post:
      tags:
      - "reminders"
      description: "Deletes a reminder."
      operationId: "reminders_delete"
      security:
      - slackAuth:
        - "reminders:write"
  /reminders.info:
    get:
      tags:
      - "reminders"
      description: "Gets information about a reminder."
      operationId: "reminders_info"
      security:
      - slackAuth:
        - "reminders:read"
  /reminders.list:
    get:
      tags:
      - "reminders"
      description: "Lists all reminders created by or for a given user."
      operationId: "reminders_list"
      security:
      - slackAuth:
        - "reminders:read"
  /rtm.connect:
    get:
      tags:
      - "rtm"
      description: "Starts a Real Time Messaging session."
      operationId: "rtm_connect"
      security:
      - slackAuth:
        - "rtm:stream"
  /search.messages:
    get:
      tags:
      - "search"
      description: "Searches for messages matching a query."
      operationId: "search_messages"
      security:
      - slackAuth:
        - "search:read"
  /stars.add:
    post:
      tags:
      - "stars"
      description: "Adds a star to an item."
      operationId: "stars_add"
      security:
      - slackAuth:
        - "stars:write"
  /stars.list:
    get:
      tags:
      - "stars"
      description: "Lists stars for a user."
      operationId: "stars_list"
      security:
      - slackAuth:
        - "stars:read"
  /stars.remove:
    post:
      tags:
      - "stars"
      description: "Removes a star from an item."
      operationId: "stars_remove"
      security:
      - slackAuth:
        - "stars:write"
  /team.accessLogs:
    get:
      tags:
      - "team"
      description: "Gets the access logs for the current team."
      operationId: "team_accessLogs"
      security:
      - slackAuth:
        - "admin"
  /team.billableInfo:
    get:
      tags:
      - "team"
      description: "Gets billable users information for the current team."
      operationId: "team_billableInfo"
      security:
      - slackAuth:
        - "admin"
  /team.info:
    get:
      tags:
      - "team"
      description: "Gets information about the current team."
      operationId: "team_info"
      security:
      - slackAuth:
        - "team:read"
  /team.integrationLogs:
    get:
      tags:
      - "team"
      description: "Gets the integration logs for the current team."
      operationId: "team_integrationLogs"
      security:
      - slackAuth:
        - "admin"
  /team.profile.get:
    get:
      tags:
      - "team.profile"
      - "team"
      description: "Retrieve a team's profile."
      operationId: "team_profile_get"
      security:
      - slackAuth:
        - "users.profile:read"
  /usergroups.create:
    post:
      tags:
      - "usergroups"
      description: "Create a User Group"
      operationId: "usergroups_create"
      security:
      - slackAuth:
        - "usergroups:write"
  /usergroups.disable:
    post:
      tags:
      - "usergroups"
      description: "Disable an existing User Group"
      operationId: "usergroups_disable"
      security:
      - slackAuth:
        - "usergroups:write"
  /usergroups.enable:
    post:
      tags:
      - "usergroups"
      description: "Enable a User Group"
      operationId: "usergroups_enable"
      security:
      - slackAuth:
        - "usergroups:write"
  /usergroups.list:
    get:
      tags:
      - "usergroups"
      description: "List all User Groups for a team"
      operationId: "usergroups_list"
      security:
      - slackAuth:
        - "usergroups:read"
  /usergroups.update:
    post:
      tags:
      - "usergroups"
      description: "Update an existing User Group"
      operationId: "usergroups_update"
      security:
      - slackAuth:
        - "usergroups:write"
  /usergroups.users.list:
    get:
      tags:
      - "usergroups.users"
      - "usergroups"
      description: "List all users in a User Group"
      operationId: "usergroups_users_list"
      security:
      - slackAuth:
        - "usergroups:read"
  /usergroups.users.update:
    post:
      tags:
      - "usergroups.users"
      - "usergroups"
      description: "Update the list of users for a User Group"
      operationId: "usergroups_users_update"
      security:
      - slackAuth:
        - "usergroups:write"
  /users.conversations:
    get:
      tags:
      - "users"
      description: "List conversations the calling user may access."
      operationId: "users_conversations"
      security:
      - slackAuth:
        - "channels:read"
        - "groups:read"
        - "im:read"
        - "mpim:read"
  /users.deletePhoto:
    post:
      tags:
      - "users"
      description: "Delete the user profile photo"
      operationId: "users_deletePhoto"
      security:
      - slackAuth:
        - "users.profile:write"
  /users.getPresence:
    get:
      tags:
      - "users"
      description: "Gets user presence information."
      operationId: "users_getPresence"
      security:
      - slackAuth:
        - "users:read"
  /users.identity:
    get:
      tags:
      - "users"
      description: "Get a user's identity."
      operationId: "users_identity"
      security:
      - slackAuth:
        - "identity.basic"
  /users.info:
    get:
      tags:
      - "users"
      description: "Gets information about a user."
      operationId: "users_info"
      security:
      - slackAuth:
        - "users:read"
  /users.list:
    get:
      tags:
      - "users"
      description: "Lists all users in a Slack team."
      operationId: "users_list"
      security:
      - slackAuth:
        - "users:read"
  /users.lookupByEmail:
    get:
      tags:
      - "users"
      description: "Find a user with an email address."
      operationId: "users_lookupByEmail"
      security:
      - slackAuth:
        - "users:read.email"
  /users.profile.get:
    get:
      tags:
      - "users.profile"
      - "users"
      description: "Retrieves a user's profile information."
      operationId: "users_profile_get"
      security:
      - slackAuth:
        - "users.profile:read"
  /users.profile.set:
    post:
      tags:
      - "users.profile"
      - "users"
      description: "Set the profile information for a user."
      operationId: "users_profile_set"
      security:
      - slackAuth:
        - "users.profile:write"
  /users.setActive:
    post:
      tags:
      - "users"
      description: "Marked a user as active. Deprecated and non-functional."
      operationId: "users_setActive"
      security:
      - slackAuth:
        - "users:write"
  /users.setPhoto:
    post:
      tags:
      - "users"
      description: "Set the user profile photo"
      operationId: "users_setPhoto"
      security:
      - slackAuth:
        - "users.profile:write"
  /users.setPresence:
    post:
      tags:
      - "users"
      description: "Manually sets user presence."
      operationId: "users_setPresence"
      security:
      - slackAuth:
        - "users:write"
securityDefinitions:
  slackAuth:
    type: "oauth2"
    authorizationUrl: "https://slack.com/oauth/authorize"
    tokenUrl: "https://slack.com/api/oauth.access"
    flow: "accessCode"
    scopes:
      admin: "admin"
      admin.users:write: "admin.users:write"
      bot: "Bot user scope"
      channels:history: "channels:history"
      channels:read: "channels:read"
      channels:write: "channels:write"
      chat:write: "chat:write"
      chat:write:bot: "Author messages as a bot"
      chat:write:user: "chat:write:user"
      conversations:history: "conversations:history"
      conversations:read: "conversations:read"
      conversations:write: "conversations:write"
      dnd:read: "dnd:read"
      dnd:write: "dnd:write"
      emoji:read: "emoji:read"
      files:read: "files:read"
      files:write:user: "files:write:user"
      groups:history: "groups:history"
      groups:read: "groups:read"
      groups:write: "groups:write"
      identity.basic: "identity.basic"
      im:history: "im:history"
      im:read: "im:read"
      im:write: "im:write"
      links:write: "links:write"
      mpim:history: "mpim:history"
      mpim:read: "mpim:read"
      mpim:write: "mpim:write"
      none: "No scope required"
      pins:read: "pins:read"
      pins:write: "pins:write"
      reactions:read: "reactions:read"
      reactions:write: "reactions:write"
      reminders:read: "reminders:read"
      reminders:write: "reminders:write"
      rtm:stream: "rtm:stream"
      search:read: "search:read"
      stars:read: "stars:read"
      stars:write: "stars:write"
      team:read: "team:read"
      tokens.basic: "tokens.basic"
      usergroups:read: "usergroups:read"
      usergroups:write: "usergroups:write"
      users.profile:read: "users.profile:read"
      users.profile:write: "users.profile:write"
      users:read: "users:read"
      users:read.email: "users:read.email"
      users:write: "users:write"